# -*- coding: utf-8 -*-
"""Proyek_Analisis_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Ld4efSwPAEENGhR4LbA5U7ItleolcCg

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** Muhammad Rizki Malik Aziz
- **Email:** rimali.qwerty@gmail.com
- **ID Dicoding:** rimali

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : "Wilayah mana (kode pos, kota) yang memiliki konsentrasi pelanggan tertinggi?"
- Pertanyaan 2 : "Bagaimana distribusi geografis pelanggan di berbagai negara bagian dan kota?"

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

"""## Data Wrangling

### Gathering Data
"""

current_dir = os.getcwd()

customers_df = pd.read_csv(os.path.join(current_dir, 'customers_dataset.csv'))
geolocation_df = pd.read_csv(os.path.join(current_dir, 'geolocation_dataset.csv'))

"""**Insight:**
- Dataset berisi informasi pelanggan dan lokasi geografisnya, yang dapat digabungkan menggunakan zip code prefix.

### Assessing Data
"""

customers_df.head()

geolocation_df.head()

"""**Insight:**
- Dataset customers dan geolocation memiliki struktur yang dapat digunakan untuk analisis geografis.

### Cleaning Data
"""

customers_df.isnull().sum()

geolocation_df.isnull().sum()

"""**Insight:**
- Tidak ada data hilang yang signifikan, jadi kita bisa langsung melakukan analisis lebih lanjut.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

customer_zip_distribution = customers_df['customer_zip_code_prefix'].value_counts()

customer_zip_distribution.head(10)

plt.figure(figsize=(10,6))
sns.barplot(x=customer_zip_distribution.head(10).index, y=customer_zip_distribution.head(10).values, hue=None, palette="magma", legend=False)
plt.title('Top 10 Kode Pos dengan Jumlah Pelanggan Tertinggi', fontsize=16)
plt.xlabel('Kode Pos', fontsize=12)
plt.ylabel('Jumlah Pelanggan', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

customers_geo = pd.merge(customers_df, geolocation_df, left_on='customer_zip_code_prefix', right_on='geolocation_zip_code_prefix', how='left')

customer_city_distribution = customers_geo['geolocation_city'].value_counts()

plt.figure(figsize=(10,6))
sns.barplot(x=customer_city_distribution.head(10).index, y=customer_city_distribution.head(10).values, palette="viridis")
plt.title('Top 10 Kota dengan Konsentrasi Pelanggan Tertinggi', fontsize=16)
plt.xlabel('Kota', fontsize=12)
plt.ylabel('Jumlah Pelanggan', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Insight:**
- Sebagian besar pelanggan terkonsentrasi di beberapa kota utama yang dapat diidentifikasi dari dataset.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

plt.figure(figsize=(10,6))
sns.barplot(x=customer_zip_distribution.head(10).index, y=customer_zip_distribution.head(10).values, color="blue")
plt.title('Top 10 Kode Pos dengan Konsentrasi Pelanggan Tertinggi', fontsize=16)
plt.xlabel('Kode Pos', fontsize=12)
plt.ylabel('Jumlah Pelanggan', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Pertanyaan 2:"""

customers_geo = pd.merge(customers_df, geolocation_df, left_on='customer_zip_code_prefix', right_on='geolocation_zip_code_prefix', how='left')

customer_city_distribution = customers_geo['geolocation_city'].value_counts()

plt.figure(figsize=(10,6))
sns.barplot(x=customer_city_distribution.head(10).index, y=customer_city_distribution.head(10).values, color="blue")
plt.title('Top 10 Kota dengan Konsentrasi Pelanggan Tertinggi', fontsize=16)
plt.xlabel('Kota', fontsize=12)
plt.ylabel('Jumlah Pelanggan', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Insight:**
- Visualisasi di atas menunjukkan kode pos dengan jumlah pelanggan tertinggi, yang bisa digunakan untuk menentukan wilayah dengan konsentrasi pelanggan paling banyak.
- Penyebaran geografis pelanggan di berbagai kota memberikan gambaran bagaimana pelanggan terdistribusi di beberapa daerah.

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclution pertanyaan 1 :
Daerah dengan konsentrasi pelanggan tertinggi dapat diidentifikasi, yang memungkinkan kita untuk fokus pada pasar tersebut.
- Conclution pertanyaan 2 :
Distribusi geografis pelanggan menunjukkan penyebaran yang bisa dimanfaatkan untuk optimalisasi pengiriman dan pemasaran.
"""